services:
  - type: web
    name: skillswap-backend
    env: python
    buildCommand: "cd skillswap_django && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd skillswap_django && gunicorn skillswap_backend.wsgi:application"
    pythonVersion: 3.12.3
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: skillswap-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: skillswap-redis
          property: connectionString
