# Generated by Django 5.2.3 on 2025-06-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning_sessions', '0002_sessionmessage'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning_sessions.learningsession'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('session', 'reviewer', 'reviewed')},
        ),
    ]
